name: basic-pipeline
on: push 
workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu:latest
    steps:
      # A step is a dictionary, and 'name' is an optional description
     - name: Print a greeting
        # 'run' executes a command-line command
       run: echo "Hello, World! GitHub Actions is running!"

     - name: Print a multiline message
       run: |
          echo "This is the first line."
          echo "This is the second line."
